{% set name = "get_version" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flying-sheep/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2d027df9c70a1a40ada1e6efade3ced168d769088b03095c843a3a65af86de73
  folder: {{ name }}-{{ version }}

build:
  noarch: python
  number: 0
  script:
    - cd "{{ name }}-{{ version }}"
    - {{ PYTHON }} -m flit install --deps none

requirements:
  host:
    - python >=3.6
    - flit >=1.3
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - get_version

about:
  home: https://github.com/flying-sheep/get_version
  license: GPL-3.0
  license_family: GPL
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Automatically use the latest “vX.X.X” Git tag as version in your Python package.
  description: |
    A version helper in the spirit of versioneer.
    Minimalistic and able to run without build step using pkg_resources.
  dev_url: https://github.com/flying-sheep/get_version

extra:
  recipe-maintainers:
    - flying-sheep
    - grst
