{% set name = "get_version" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flying-sheep/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e2db57b926c735de6f2d3f68055e421000797008debeaffb7764adf2b6e8fa82
  folder: {{ name }}-{{ version }}

build:
  noarch: python
  number: 0
  script:
    - cd "{{ name }}-{{ version }}"
    - {{ PYTHON }} -m pip install --use-feature=in-tree-build .

requirements:
  host:
    - python >=3.7
    - flit >=1.3
  run:
    - python >=3.7
    - dunamai
    - importlib_metadata

test:
  imports:
    - get_version

about:
  home: https://github.com/flying-sheep/get_version
  license: GPL-3.0
  license_family: GPL
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Automatically use the latest “vX.X.X” Git tag as version in your Python package.
  description: |
    A version helper in the spirit of versioneer.
    Minimalistic and able to run without build step using pkg_resources.
  dev_url: https://github.com/flying-sheep/get_version

extra:
  recipe-maintainers:
    - flying-sheep
    - grst
