{% set name = "get_version" %}
{% set version = "3.5.5" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/flying-sheep/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 25be900567cd89934cd275802da9f1ddfd526d55661489a985599ff101155726
  folder: {{ name }}-{{ version }}

build:
  noarch: python
  number: 0
  script:
    - cd "{{ name }}-{{ version }}"
    - {{ PYTHON }} -m pip install --use-feature=in-tree-build .

requirements:
  host:
    - python >=3.9
    - flit >=1.3
  run:
    - python >=3.9
    - git
    - dunamai >=1.19.0

test:
  imports:
    - get_version

about:
  home: https://github.com/flying-sheep/get_version
  license: GPL-3.0
  license_family: GPL
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Automatically use the latest “vX.X.X” Git tag as version in your Python package.
  description: |
    A version helper in the spirit of versioneer.
    Minimalistic and able to run without build step using pkg_resources.
  dev_url: https://github.com/flying-sheep/get_version

extra:
  recipe-maintainers:
    - flying-sheep
    - grst
