travis:
  secure:
    BINSTAR_TOKEN: Vbe+/QOrHstgP+f07ybJOZy9LBXPBTwVY7C5L1XBzzw5KQn4oN7/9IknWW5/8+NA89e9XiMGUJ4tR8ToKSphzNzJzTk2xd5GgMtZ3Yl6GetZ+zwhU+k9K0c47qJi74uf0fov5kWvUeSe4skyqhLLxHy6lYVpcQ52yO8a2Vw8hGbElPk9tXX4Bz6cABkj8TxqQhnPPIjgbNVIOUSlu5d0DeOCv3Prbz0EHzS/JNS6U3x1/oM5fv6jCxWO4Mk1tQTfSYzFNSvosAv4jIjJuXTGAVVE0TGP4BAlpSKOXdbDsLGYrz21C7Eg85TG5J9rJFrwXF4sWLz6WAZI+2sO83dl7LPtNWd4ucT1nAcakW4RX6lNw7COxeWJ/aE7TCs6y+FFJdKsOBgYkLV0zfBoMCzIFWXT6EF/pDT96zybBOLUXVV80SU4RE2vROx2tvr0dyAjsCRUTZQMel3guVKmSDRst0b+f/5g9o0VfTJAirODMzDRwOg9zJeXzWu0fPSoQ2jfjBjmhjM7U++tvIgVikQdI4b2k7D0k61SPVDSP4Eq4x354SNallJQ1avsNAeRBxlPj32SyaM0okIgPoczeeCa/sGik3bE5jT8r53HMaHGGJonK+VsBjohFRHORTgE61D7kZKJSw5WznWUlvLEDhdGyNDuaMNWKnyLXM1z/J9Ex/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
